### PR TITLE
Added State Emum class, added Spin Method and corresponding tests

### PR DESCRIPTION
**Pull request by klambo94**

### CODE REVIEW

**Comment by klambo94** [comment]
I realized I did not put any appendTrace calls for spin when not failing. Please implement this either in code review changes or next do method (PEEK or POKE)

**Comment by klambo94** [comment]
@maxthunder  I implemented the code review suggestions - I agree with the multiple returns that removing them makes it more maintainable. Please review that change to see if there may be a better way (neater) to do this. If not Please merge into master if everything else looks good.

**Comment by alicerowan** [comment]
Is the `State` class intended for submission?  I ask because our deliverable is specified to be exactly one .java file named **FourBitTwoDisclosureDeviceUnlocker.java**.

**Comment by klambo94** [comment]
Commit on 9/14 at 10:38 removed state class, updated the corresponding files. I also imported List<> into device. Updated spelling of 'feild' -> 'field' in tests. I also refactored the doSpin method.

**Pull request merged**
